bank/bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('clientes/', include('clientes.urls')),
    path('admin/', admin.site.urls),
]

bank/clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'
urlpatterns = [
    path('', views.index, name='index'),
    path('crear/', views.crear_cliente, name='crear_cliente'),
    path('detalle/<int:id_cliente>', views.detalle, name='detalle'),
    path('cuentas/crear/<int:id_cliente>', views.crear_cuenta, name='crear_cuenta'),
    path('borrar/<int:id_cliente>', views.borrar_cliente, name='borrar_cliente'),
    path('cuentas/borrar/<int:id_cliente>/<int:id_cuenta>', views.borrar_cuenta, name='borrar_cuenta'),
]

bank/clientes/models.py
from django.db import models


# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_registro = models.DateTimeField()

    def __str__(self):
        return self.nombre


class Cuenta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    categoria = models.CharField(max_length=30, default='normal')
    balance = models.IntegerField(default=0)

bank/clientes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from .models import Cliente, Cuenta


# Create your views here.
def index(request):
    """Desplegar todos los clientes"""
    # obtener clientes de la DB
    clientes = Cliente.objects.all()
    context = {'lista_clientes': clientes}

    return render(request, 'clientes/index.html', context)


def crear_cliente(request):
    nombre = request.POST['nombre']
    nuevo_cliente = Cliente(nombre=nombre, fecha_registro=timezone.now())
    nuevo_cliente.save()
    return HttpResponseRedirect(reverse('clientes:index'))


def detalle(request, id_cliente):
    # verificar si el cliente existe
    cliente = get_object_or_404(Cliente, pk=id_cliente)
    # print('cuentas:', cliente.cuenta_set.count())
    cuentas = cliente.cuenta_set.all()
    context = {'cliente': cliente, 'lista_cuentas': cuentas}
    return render(request, 'clientes/detalle.html', context)


def crear_cuenta(request, id_cliente):
    categoria = request.POST['categoria']
    # verificar si el cliente existe
    cliente = get_object_or_404(Cliente, pk=id_cliente)
    cuenta = Cuenta(categoria=categoria, cliente=cliente)
    cuenta.save()
    return HttpResponseRedirect(reverse('clientes:detalle', args=[id_cliente]))


def borrar_cliente(request, id_cliente):
    cliente = get_object_or_404(Cliente, pk=id_cliente)
    cliente.delete()    # se elimina de la DB
    return HttpResponseRedirect(reverse('clientes:index'))


def borrar_cuenta(request, id_cliente, id_cuenta):
    cliente = get_object_or_404(Cliente, pk=id_cliente)
    cuenta = get_object_or_404(Cuenta, pk=id_cuenta)
    cuenta.delete()
    return HttpResponseRedirect(reverse('clientes:detalle', args=[id_cliente]))

bank/clientes/templates/clientes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banco Django - {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'clientes/estilos/style.css' %}">
</head>
<body>
    <h1>Banco Django - 
    {% block header %}
    {% endblock %}
    </h1>
    {% block content %}
    {% endblock %}
</body>
</html>

bank/clientes/templates/clientes/detalle.html
{% extends 'clientes/base.html' %}
{% load static %}
{% block content %}
<img src="{% static 'clientes/img/gato.jpg' %}" alt="gato">
<a href="{% url 'clientes:index' %}">Volver</a><br>
Fecha de Registro: {{ cliente.fecha_registro }} <br>

<form action="{% url 'clientes:crear_cuenta' cliente.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="categoria" id="categoria"><label for="categoria">Categoria</label>
    <input type="submit" value="Abrir Cuenta">
</form>

<h3>Cuentas:</h3>
{% if lista_cuentas %}
<ul>
    {% for cuenta in lista_cuentas %}
    <li>
        id: {{ cuenta.id }} -- Cat: {{ cuenta.categoria }} -- Balance: {{ cuenta.balance }} 
        <a href="{% url 'clientes:borrar_cuenta' cliente.id cuenta.id %}">Borrar</a>
    </li>
    {% endfor %}
</ul>
{% else %}
Este cliente, no tiene cuentas!
{% endif %}

{% endblock %}


{% block title %} Detalle {% endblock %}

{% block header %} Detalle Cliente: {{ cliente.nombre }} {% endblock %}

bank/clientes/templates/clientes/index.html
{% extends 'clientes/base.html' %}
{% block title %} Clientes {% endblock %}

{% block header %} Clientes {% endblock %}

{% block content %}
    <form action="{% url 'clientes:crear_cliente' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="nombre" id="nombre"><label for="nombre">Nombre</label>
        <input type="submit" value="Crear Cliente">
    </form>
    {% if lista_clientes %}
    <ul>
        {% for cliente in lista_clientes %}
        <li>{{ cliente.id }}: 
            <a href="{% url 'clientes:detalle' cliente.id %}">{{ cliente.nombre }}</a>
            ---
            cuentas: {{ cliente.cuenta_set.count }} 
            <a href="{% url 'clientes:borrar_cliente' cliente.id %}">Borrar</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <h4>No hay clientes que mostrar :c</h4>
    {% endif %}
{% endblock %}