laboratorio/inventario/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required
from .views import ItemView, ItemDetailView, EncargadoDetailView, PrestamoListView, EncargadoListView


app_name = 'inventario'
urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='inventario/index.html'),
        name='index'
    ),
    path(
        'items/',
        ItemView.as_view(),
        name='items'
    ),
    path(
        'items/detalle/<slug:slug>/',
        ItemDetailView.as_view(),
        name='detalle_item'
    ),
    path(
        'encargados/',
        EncargadoListView.as_view(),
        name='encargados'
    ),
    path(
        'encargados/detalle/<slug:slug>/',
        EncargadoDetailView.as_view(),
        name='detalle_encargado'
    ),
    path(
        'prestamos/',
        PrestamoListView.as_view(),
        name='prestamos'
    ),
]

laboratorio/laboratorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventario/', include('inventario.urls')),
    path('admin/', admin.site.urls),
]

laboratorio/inventario/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=150)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Encargado(models.Model):
    CARRERA_CHOICES = [
        ('ETN', 'Electrónica'),
        ('MEC', 'Mecánica'),
        ('TEL', 'Telecomunicaciones'),
    ]
    nombre = models.CharField(max_length=200)
    carrera = models.CharField(max_length=3, choices=CARRERA_CHOICES, default='ETN')
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Item(models.Model):
    nombre = models.CharField(max_length=150)
    marca = models.CharField(max_length=150)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.SET_NULL, null=True)
    cantidad = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def is_available(self):
        return self.cantidad > 0

    def __str__(self):
        return f'{self.marca}:{self.nombre}'


class Prestamo(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    fecha_prestamo = models.DateTimeField(auto_now_add=True)
    fecha_devolucion = models.DateTimeField(null=True)

    def __str__(self):
        return f'{self.item}: {self.fecha_prestamo}'

laboratorio/inventario/forms.py
from django import forms
from .models import Item, Categoria, Encargado, Prestamo


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']


class EncargadoForm(forms.ModelForm):
    class Meta:
        model = Encargado
        fields = ['nombre', 'carrera']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['nombre', 'marca', 'categoria', 'encargado', 'cantidad']


class PrestamoItemForm(forms.Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput())

laboratorio/inventario/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView
from .models import Item, Encargado, Prestamo, Categoria
from .forms import ItemForm, PrestamoItemForm


class CrearYListarView(View):
    name = 'objects'
    template = 'default'
    form = None
    model = None

    def get(self, request):
        return render(
            request,
            self.template,
            {
                self.name: self.model.objects.all(),
                'form': self.form()
            }
        )

    def post(self, request):
        form = self.form(request.POST)
        form.save()
        return HttpResponseRedirect(reverse(f'inventario:{self.name}'))


class ItemView(CrearYListarView):
    name = 'items'
    template = 'inventario/items.html'
    form = ItemForm
    model = Item


class ItemDetailView(DetailView):
    model = Item
    template_name = 'inventario/detalle_item.html'
    slug_field = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        prestamo_form = PrestamoItemForm({'item_id': context['object'].id})
        context['prestamo_form'] = prestamo_form
        return context

    def post(self, request, slug):
        prestamo_form = PrestamoItemForm(request.POST)
        if prestamo_form.is_valid():
            item = Item.objects.get(pk=prestamo_form.cleaned_data['item_id'])
            prestamo = Prestamo(item=item)
            prestamo.save()
            if item.cantidad > 0:
                item.cantidad -= 1
                item.save()

        return HttpResponseRedirect(reverse('inventario:items'))


class EncargadoDetailView(DetailView):
    model = Encargado
    template_name = 'inventario/detalle_encargado.html'
    slug_field = 'id'


class PrestamoListView(ListView):
    model = Prestamo
    context_object_name = 'prestamos'
    template_name = 'inventario/prestamos.html'


class EncargadoListView(ListView):
    model = Encargado
    context_object_name = 'encargados'
    template_name = 'inventario/encargados.html'

laboratorio/inventario/templates/inventario/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laboratorio: {% block title %}{% endblock %}</title>
</head>
<body>
<h2>
{% block header %}{% endblock %}
</h2>
<hr>
<a href="{% url 'inventario:items' %}">Items</a> - <a href="{% url 'inventario:encargados' %}">Encargados</a> - <a
        href="{% url 'inventario:prestamos' %}">Prestamos</a> <br>
<hr>
{% block body %}{% endblock %}
</body>
</html>

laboratorio/inventario/templates/inventario/detalle_encargado.html
{% extends 'inventario/base.html' %}
{% block title %}
Encargado
{% endblock %}

{% block header %}
Encargado
{% endblock %}

{% block body %}
<h2>{{ object.nombre }}</h2>
<h3>{{ object.carrera }}</h3>
<b>id:</b> {{ object.id }} <br>
<b>fecha de creacion:</b> {{ object.fecha_registro }}
{% endblock %}

laboratorio/inventario/templates/inventario/detalle_item.html
{% extends 'inventario/base.html' %}
{% block title %}
    Detalle Item
{% endblock %}

{% block header %}
    Detalle Item
{% endblock %}

{% block body %}
    <h2>{{ object.nombre }}</h2>
    <h3>{{ object.marca }}</h3>
    <b>id:</b> {{ object.id }} <br>
    <b>categoria:</b> {{ object.categoria }} <br>
    <b>encargado:</b> {{ object.encargado }} <br>
    <b>cantidad:</b> {{ object.cantidad }} <br>
    <b>fecha de creacion:</b> {{ object.fecha_creacion }}

    {% if object.is_available %}
    <form action="{% url 'inventario:detalle_item' object.id%}" method="POST">
        {% csrf_token %}
        {{ prestamo_form }}
        <input type="submit" value="Solicitar Prestamo">
    </form>
        {% else %}
        <h3>Item no disponible</h3>
    {% endif %}
{% endblock %}

laboratorio/inventario/templates/inventario/encargados.html
{% extends 'inventario/base.html' %}
{% block title %}
Encargados
{% endblock %}

{% block header %}
Encargados
{% endblock %}

{% block body %}
{% if encargados %}
    <table border="1">
        <tr>
            <th>Nombre</th>
            <th>Carrera</th>
            <th>Fecha de Registro</th>
        </tr>
        {% for encargado in encargados %}
            <tr>
                <td>{{ encargado.nombre }}</td>
                <td>{{ encargado.carrera }}</td>
                <td>{{ encargado.fecha_registro }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen encargados!</h3>
{% endif %}
{% endblock %}

laboratorio/inventario/templates/inventario/index.html
{% extends 'inventario/base.html' %}
{% block title %}
Home
{% endblock %}
{% block header %}
Home
{% endblock %}
{% block body %}
<h1>Bienvenidos!</h1>
Bienvenidos al sistema de inventario
{% endblock %}

laboratorio/inventario/templates/inventario/items.html
{% extends 'inventario/base.html' %}
{% block title %}
Items
{% endblock %}

{% block header %}
Items
{% endblock %}

{% block body %}
<form action="{% url 'inventario:items' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Crear Item">
</form>

{% if items %}
    <table border="1">
        <tr>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Categoria</th>
            <th>Detalle</th>
        </tr>
        {% for item in items %}
            <tr>
                <td>{{ item.nombre }}</td>
                <td>{{ item.marca }}</td>
                <td>{{ item.categoria }}</td>
                <td><a href="{% url 'inventario:detalle_item' item.id%}">Detalle</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen items!</h3>
{% endif %}
{% endblock %}

laboratorio/inventario/templates/inventario/prestamos.html
{% extends 'inventario/base.html' %}
{% block title %}
Prestamos
{% endblock %}

{% block header %}
Prestamos
{% endblock %}

{% block body %}
{% if prestamos %}
    <table border="1">
        <tr>
            <th>Item</th>
            <th>Fecha de Prestamo</th>
            <th>Fecha de Devolución</th>
        </tr>
        {% for prestamo in prestamos %}
            <tr>
                <td><a href="{% url 'inventario:detalle_item' prestamo.item.id %}">{{ prestamo.item }}</a></td>
                <td>{{ prestamo.fecha_prestamo }}</td>
                <td>{{ prestamo.fecha_devolucion }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen prestamos!</h3>
{% endif %}
{% endblock %}