tareas/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('log_user/', views.login_user, name='login')
]

tareas/lista_tareas/urls.py
from django.urls import path
from . import views


app_name = 'lista_tareas'
urlpatterns = [
    path('', views.listar_tareas, name='listar_tareas'),
    path('crear/', views.crear_tarea, name='crear_tarea'),
    path('eliminar/', views.eliminar_tarea, name='eliminar_tarea'),
    path('clientes/', views.clientes, name='clientes'),
]

tareas/tareas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tareas/', include('lista_tareas.urls')),
    path('authentication/', include('authentication.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

tareas/authentication/models.py
from django.db import models

# Create your models here.

tareas/lista_tareas/models.py
from django.db import models


# Create your models here.
class Tarea(models.Model):
    texto = models.CharField(max_length=300)
    prioridad = models.IntegerField(default=0)
    fecha_creacion = models.DateTimeField()
    

class Cliente(models.Model):
    nombre = models.CharField(max_length=150)
    edad = models.IntegerField()
    fecha_nacimiento = models.DateField()
    score = models.DecimalField(decimal_places=2, max_digits=6)
    

tareas/lista_tareas/forms.py
from django import forms
from .models import Cliente

class CrearTareaForm(forms.Form):
    texto = forms.CharField(label='Texto ', max_length=300)
    prioridad = forms.IntegerField(label='Prioridad ', max_value=10, min_value=0)


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'edad', 'fecha_nacimiento', 'score']

tareas/authentication/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate


# Create your views here.
def login_user(request):
    user = authenticate(
        username=request.POST['username'],
        password=request.POST['password']
    )
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('lista_tareas:listar_tareas'))
    else:
        return HttpResponse('no existe', status=403)


def login_view(request):
    return render(request, 'authentication/login.html')

tareas/lista_tareas/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from .models import Cliente, Tarea
from .forms import CrearTareaForm, ClienteForm


@login_required
def listar_tareas(request):
    print(request.user.has_perm('lista_tareas.add_tarea'))
    tareas = Tarea.objects.all()
    context = {
        'lista_tareas': tareas,
        'crear_form': CrearTareaForm()
        }
    return render(request, 'lista_tareas/index.html', context)


#                       nombre_app.permiso([add, change, delete, view]_{modelo})
@permission_required('lista_tareas.add_tarea')
def crear_tarea(request):
    form = CrearTareaForm(request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        tarea = Tarea(
            texto=form.cleaned_data['texto'],
            prioridad=form.cleaned_data['prioridad'],
            fecha_creacion=timezone.now()
        )
        tarea.save()
    
    return HttpResponseRedirect(reverse('lista_tareas:listar_tareas'))


def eliminar_tarea(request, id_tarea):
    tarea = get_object_or_404(Tarea, pk=id_tarea)
    tarea.delete()
    return HttpResponseRedirect(reverse('lista_tareas:listar_tareas'))


def clientes(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('lista_tareas:clientes'))
    else:
        clientes = Cliente.objects.all()
        form = ClienteForm()
        context = {
            'clientes': clientes,
            'form': form
        }
        return render(request, 'lista_tareas/clientes.html', context)

tareas/authentication/templates/authentication/login.html
<form action="{% url 'authentication:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" id="username"><label for="username">username</label><br>
    <input type="text" name="password" id="password"><label for="password">contraseña</label><br>
    <input type="submit" value="Ingresar">
</form>

tareas/lista_tareas/templates/lista_tareas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tareas/lista_tareas/templates/lista_tareas/clientes.html
<form action="{% url 'lista_tareas:clientes' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Crear Tarea">
</form>

{% if clientes %}
<ul>
    {% for cliente in clientes %}
    <li>
        {{ cliente.nombre }}: {{ cliente.edad }}
    </li>
    {% endfor %}
</ul>
{% else %}
<h3>No existen clientes!</h3>
{% endif %}

tareas/lista_tareas/templates/lista_tareas/index.html
<form action="{% url 'lista_tareas:crear_tarea' %}" method="POST">
    {% csrf_token %}
    {{ crear_form }}
    <input type="submit" value="Crear Tarea">
</form>
{% if lista_tareas %}
    <ol>
        {% for tarea in lista_tareas %}
            <li>{{ tarea.texto }} --- Prioridad: {{ tarea.prioridad }}</li>
        {% endfor %}
    </ol>
{% else %}
    <h4>No hay tareas que mostrar :)</h4>
{% endif %}

<a href="{% url 'logout' %}">Cerrar Sesion</a>