almacen/almacen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventario/', include('inventario.urls')),
    path('admin/', admin.site.urls),
]

almacen/inventario/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required
from .views import ItemView, CategoriaView, EncargadosListView, ItemDetailView, EncargadoDetailView


app_name = 'inventario'
urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='inventario/index.html'),
        name='index'
    ),
    path(
        'items/',
        login_required(ItemView.as_view()),
        name='items'
    ),
    path(
        'categorias/',
        permission_required('inventario.add_categoria')(CategoriaView.as_view()),
        name='categorias'
    ),
    path(
        'encargados/',
        EncargadosListView.as_view(),
        name='encargados'
    ),
    path(
        'items/detalle/<slug:slug>/',
        ItemDetailView.as_view(),
        name='detalle_item'
    ),
    path(
        'encargados/detalle/<slug:slug>/',
        EncargadoDetailView.as_view(),
        name='detalle_encargado'
    ),
]

almacen/inventario/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=150)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Encargado(models.Model):
    CARRERA_CHOICES = [
        ('ETN', 'Electrónica'),
        ('MEC', 'Mecánica'),
        ('TEL', 'Telecomunicaciones'),
    ]
    nombre = models.CharField(max_length=200)
    carrera = models.CharField(max_length=3, choices=CARRERA_CHOICES, default='ETN')
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Item(models.Model):
    nombre = models.CharField(max_length=150)
    marca = models.CharField(max_length=150)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.SET_NULL, null=True)
    cantidad = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.marca}:{self.nombre}'

almacen/inventario/forms.py
from django import forms
from .models import Item, Categoria, Encargado


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']


class EncargadoForm(forms.ModelForm):
    class Meta:
        model = Encargado
        fields = ['nombre', 'carrera']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['nombre', 'marca', 'categoria', 'encargado', 'cantidad']

almacen/inventario/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Item, Categoria, Encargado
from .forms import ItemForm, CategoriaForm


class EncargadosListView(ListView):
    model = Encargado
    context_object_name = 'encargados'


class CrearYListarView(View):
    name = 'objects'
    template = 'default'
    form = None
    model = None

    def get(self, request):
        return render(
            request,
            self.template,
            {
                self.name: self.model.objects.all(),
                'form': self.form()
            }
        )

    def post(self, request):
        form = self.form(request.POST)
        form.save()
        return HttpResponseRedirect(reverse(f'inventario:{self.name}'))


class ItemView(CrearYListarView):
    name = 'items'
    template = 'inventario/items.html'
    form = ItemForm
    model = Item


class ItemDetailView(DetailView):
    model = Item
    template_name = 'inventario/detalle_item.html'
    slug_field = 'id'


class EncargadoDetailView(DetailView):
    model = Encargado
    template_name = 'inventario/detalle_encargado.html'
    slug_field = 'id'


class CategoriaView(CrearYListarView):
    name = 'categorias'
    template = 'inventario/categorias.html'
    form = CategoriaForm
    model = Categoria



@login_required
def items(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('inventario:items'))
    else:
        items_list = Item.objects.all()
        form = ItemForm()
        context = {
            'items': items_list,
            'form': form
        }
        return render(request, 'inventario/items.html', context)

almacen/inventario/templates/inventario/categorias.html
<form action="{% url 'inventario:categorias' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Crear Categoria">
</form>

{% if categorias %}
    <table border="1">
        <tr>
            <th>Nombre</th>
            <th>Fecha Creación</th>
        </tr>
        {% for categoria in categorias %}
            <tr>
                <td>{{ categoria.nombre }}</td>
                <td>{{ categoria.fecha_creacion }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen categorias!</h3>
{% endif %}

almacen/inventario/templates/inventario/detalle_encargado.html
<h2>{{ object.nombre }}</h2>
<h3>{{ object.carrera }}</h3>
<b>id:</b> {{ object.id }} <br>
<b>fecha de creacion:</b> {{ object.fecha_registro }}

almacen/inventario/templates/inventario/detalle_item.html
<h2>{{ object.nombre }}</h2>
<h3>{{ object.marca }}</h3>
<b>id:</b> {{ object.id }} <br>
<b>categoria:</b> {{ object.categoria }} <br>
<b>encargado:</b> {{ object.encargado }} <br>
<b>cantidad:</b> {{ object.cantidad }} <br>
<b>fecha de creacion:</b> {{ object.fecha_creacion }}

almacen/inventario/templates/inventario/encargado_list.html
{% if encargados %}
    <table border="1">
        <tr>
            <th>Nombre</th>
            <th>Carrera</th>
        </tr>
        {% for encargado in encargados %}
            <tr>
                <td><a href="{% url 'inventario:detalle_encargado' encargado.id %}">{{ encargado.nombre }}</a></td>
                <td>{{ encargado.carrera }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen encargados!</h3>
{% endif %}

almacen/inventario/templates/inventario/index.html
<h1>Bienvenidos!</h1>
<ul>
    <li><a href="{% url 'inventario:items' %}">Items</a></li>
    <li><a href="{% url 'inventario:encargados' %}">Encargados</a></li>
</ul>

almacen/inventario/templates/inventario/items.html
<form action="{% url 'inventario:items' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Crear Item">
</form>

{% if items %}
    <table border="1">
        <tr>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Categoria</th>
            <th>Detalle</th>
        </tr>
        {% for item in items %}
            <tr>
                <td>{{ item.nombre }}</td>
                <td>{{ item.marca }}</td>
                <td>{{ item.categoria }}</td>
                <td><a href="{% url 'inventario:detalle_item' item.id%}">Detalle</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No existen items!</h3>
{% endif %}